### ISSUE TITLE
clarifications about batches, normalization, and comparative analysis

### ISSUE THREAD

**Issue by vagarwal87** [YosefLab/MPRAnalyze#5]
Hi,

Thank you for providing an excellent package. Reading through the vignette, I had a few questions that I was slightly confused about, and would greatly appreciate if you could help clarify.

1) In your code below, is there any reason you used totsum for dna and uq for rna? Would you recommend using the default uq for both rna and dna?

```
obj <- estimateDepthFactors(obj, lib.factor = c("batch", "condition"),
                            which.lib = "dna", 
                            depth.estimator = "totsum")
obj <- estimateDepthFactors(obj, lib.factor = c("condition"),
                            which.lib = "rna", 
                            depth.estimator = "uq")
```

2) Is it possible to incorporate multiple batches to account for? Something like this for example:

```
obj <- analyze.quantification(obj = obj, 
                              dnaDesign = ~ barcode + batch1 + batch2 + condition,
                              rnaDesign = ~ condition)
```

3) For comparative analysis you provided this code:

```
obj <- analyze.comparative(obj = obj, 
                           dnaDesign = ~ barcode + batch + condition, 
                           rnaDesign = ~ condition, 
                           reducedDesign = ~ 1)
```

Lets say instead of 2 conditions, there are 5: WT, Mut, A, B, C, and we would like to compare C to A, B to Mut, etc. What is the appropriate syntax to compare any 2 libraries which we specify?

4) As far as I can tell, this package assumes a fixed number of barcodes per insert. Can this package accommodate the possibility that each insert might have a different number of barcodes? Lets say we have this situation:

Insert 1: 60 barcodes
Insert 2: 30 barcodes
Insert 3: 40 barcodes

Then can the package generalize to a 3 insert x 60 barcode data frame, filling in 0s for cases that have no barcode?

Best,
Vikram

**Comment by davidsebfischer** [comment]
Hi Vikram,

thanks for your interest! 
**2.** You can set up any linear model for both DNA and RNA, this means that you can include as many confounders as you want. Note though: If batch1 and batch2 are two batches of the same confounder (let's say two experimental replicates), then these terms appear in the same column in the cell annotation table (ie column 'batch' with entries batch1 or batch2 for each cell) and your model has to be ~ barcode + batch + condition. If by batch1 and batch2 you mean independent confounders, for example experimental replicate and sequencing batch, then your formulation is correct.

**3.** If you are interested in a specific subset of comparisons, one way to go would be to conduct independent pair-wise tests: Reduce the data set to the data from a given pair of conditions and conduct the test as you proposed. Let us know if you are interested in the (combinatorial) set of all pair-wise comparisons.

I'll talk to Tal about 1. and 4. and we will come back to you!
Best,
David

**Comment by talashuach** [comment]
Hi Vikram,
Thanks for using the package!

1. that code is mostly there to demonstrate the syntax of library normalization. Generally we do recommend using the uq normalization, which is the default behavior.

3. Adding to David's reply: if you are interested in pairwise comparisons, we do support coefficient-based testing (using a Wald test on the regression coefficients). However - this currently requires having a single reference condition, against which all the others are compared. 
You can determine which factor is the reference by changing which value is the first level of the 'condition' factor.
So if you want to compare A vs Mut, B vs. Mut, C vs. Mut - all of those can be done with a single run of the analysis function, by setting "Mut" as the reference. f you also want to compare A vs. B, that requires running the analysis again with A or B as the reference value. If you are interested in all pairs comparisons for N possible values, that'll currently require N-1 runs of the analysis, to cover all possible pairs.
We are working on an option of doing all-pairs more conveniently.

In the meanwhile, to use the coefficient-based testing instead of likelihood-ratio, you need to tell the analysis function to fit the standard errors (by setting fit.se=TRUE), and you don't need to supply a redced model. [Note that this does make the analysis run a bit slower]
Then after fitting the model the testing is done with the test.coefficient function, to which you need to specify which factor and which value to test (a separate test for each value).

So it should look something like:
```
obj <- analyze.comparative(obj = obj, 
                           dnaDesign = ~ barcode + batch + condition, 
                           rnaDesign = ~ condition, 
                           fit.se=TRUE)
results <- test.coefficent(obj = obj, factor="condition", contrast=<the contrast to use>)
```
This will compare the contrast provided with the reference value (so if Mut is the reference, set it to "A" and it'll compare A to Mut, "B" will compare B to Mut, etc.)

Note that this testing scheme sometimes has some issues (in which case warning will be printed out), but it should work fine for the vast majority of cases. Please let me know if it's giving you any trouble!
It will also be added to the vignette soon.

And alternative to this, if it still causes issues, is to do the pair-wise analysis that David suggested, by ust reduced the data to only include the pair you're interested in.

4. That is exactly what needs to be done (padding with 0's), but currently the user has to do that before giving the data to the package, which indeed expects all inserts to have the same number of barcodes. Maybe we'll add that functionality to future versions!

Best,
Tal

**Comment by vagarwal87** [comment]
Thank you for the clarifications, David and Tal! That helps me greatly and answers all of the questions I can think of for now. Will re-open later if I get stuck experimenting with the suggestions or can think of more questions down the road.

Best,
Vikram

**Comment by vagarwal87** [comment]
Sorry but I just had one more question that emerged when trying to pre-process the data into the correct form. I'm not fully sure how barcodes are being modeled internally. Should they always obey a fixed structure across conditions?

Let's say again we have WT, Mut, A, B, and C conditions again, and for insert 1 it has been observed with 30, 80, 140, 70, and 300 barcodes across each of the 5 conditions, respectively. Does that mean for that row 1, it should be a sparse 5 x 300 vector, in which columns 1, 301, 601, 901, and 1201 should match the same barcode; 2, 302, 602, 902, and 1202 should match the same barcode; etc etc? Then the same would hold true for a separate group of barcodes for insert 2, 3, etc? Or theoretically, if the barcodes were all permuted and in random order per condition, it would lead to the same result? That is, should the barcode dimensionality be identical for each group of conditions/replicates for the DNA? Likewise, the same ordering of barcodes should be preserved for the RNA counts? You mention this:

> Note that while this datset is "paired", and therefore the dimensionality of the two matrices and the annotations are identical, this is not always the case, and separate data frames can be used for the DNA and RNA annotations.

Can you elaborate on this point a bit? I was thinking before that the dimensionality and ordering of the barcodes should be identical among DNA/RNA as all barcodes are queried in both. What is a case in which they would be unpaired for example?

**Comment by talashuach** [comment]
Hi Vikram,

Assuming you are modeling barcodes (including them in the DNA model): the barcodes are modeled internally similarly to an additional batch factor in the DNA model (meaning - each barcode has a separate DNA estimate). Similar to a batch factor, the order of the barcodes doesn't really matter, as long as the annotations accurately reflect which count came from which barcode.
So if the barcodes maintain their order (which is usually the easiest to do, formatting-wise), then your annotations data.frame should have a column of the format:
Column    Barcode      Condition
1               1                 A
2               2                 A
...
301           1                 B
302           2                 B
...
601           1                 C
602           2                 C
...

etc. Where, as before, missing barcodes should be padded with 0s.
You can change the order any way you want, as long as the annotations are correct.
Note that since the annotations are shared among all inserts, whatever format you chose will need to be the same for the entire experiment.

This is only true if you model barcodes (which is recommended). If you don't include the barcode factor in the DNA model, then you can change the barcode ordering any way you want, the results will not change.
I hope this answers the first part of you question.

As to the question of pairing - this is important to determine which factors in the DNA model are informative to the RNA model, and is mostly useful for various condition\batch factors, דןמבק the barcode factor is almost always carried between the two models.
I'll try to explain the idea better:
Say there's an MPRA experiment with 3 replicates. That can mean two different things:
**Unpaired**: if the DNA counts originate from the pre-transduction plasmid library, then we have 3 DNA-seq replicates of the plasmid library and 3 RNA-seq replicates of the post-transduction cell population (either technical or biological replicates). Essentially, the DNA replicates are independent of the RNA replicates.
So if barcode X had higher counts for DNA replicate 1, we won't expect that to mean that barcode X will have higher RNA counts in RNA replicate 1. In this case, you should avoid modeling the replicates (meaning, avoid including the "replicate" factor in the design) in the DNA model. The results will be that the DNA estimates will be implicitly averaged across the DNA replicates.
**paired**: if, however, the DNA counts originated from the same post-tranduction populations as the RNA counts, then if barcode X had higher counts in DNA replicate 1, that would conceptually mean that barcode X was in fact more abundant in replicate 1, and we therefore would expect barcode 1 to have higher RNA counts in the RNA replicate 1. You can tell the model to use that information simply by modeling the replicate (include the replicate factor in the design) in the DNA model.

As I said, this is mostly useful for various condition\batch factors. The barcodes are a special case, since even in an unpaired setting, if barcode X had higher DNA counts in he pre-transduction library we would expect it to be more abundant in the actual post-transduction cell population, and therefor have higher RNA counts.
So generally, barcode information should be modeled in the DNA model if possible, since it is almost always informative to the RNA model.

I hope this answers your question, please let me know if anything remains unclear.
These questions are very helpful to know which parts of the vignette\documentation we should expand on.

Best,
Tal
